const bollyser=[
  {
    "title": "Sacred Games",
    "genre": ["Crime", "Thriller", "Drama"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/1.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Mirzapur",
    "genre": ["Action", "Crime", "Drama"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/2.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Family Man",
    "genre": ["Action", "Drama", "Comedy"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.7,
     "imagepath": "/bollyimages/3.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Paatal Lok",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/4.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Made in Heaven",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.3,
     "imagepath": "/bollyimages/5.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Delhi Crime",
    "genre": ["Crime", "Drama", "Police Procedural"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/6.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Breathe (incl. Into the Shadows)",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/7.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Inside Edge",
    "genre": ["Drama", "Sport"],
    "year_of_release": 2017,
    "seasons": 3,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/8.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Criminal Justice",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.1,
     "imagepath": "/bollyimages/9.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Asur",
    "genre": ["Crime", "Psychological Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "JioCinema",
    "iconpath": "/icons/jiocinema.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/10.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Panchayat",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.9,
     "imagepath": "/bollyimages/11.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Gullak",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2019,
    "seasons": 4,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 9.2,
     "imagepath": "/bollyimages/12.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kota Factory",
    "genre": ["Drama"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 9.0,
     "imagepath": "/bollyimages/13.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "TVF Pitchers",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2015,
    "seasons": 2,
    "where_to_watch": "Zee5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 9.1,
     "imagepath": "/bollyimages/14.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hostel Daze",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2019,
    "seasons": 4,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/15.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Aspirants",
    "genre": ["Drama"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 9.2,
     "imagepath": "/bollyimages/16.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Flames",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.7,
     "imagepath": "/bollyimages/17.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Yeh Meri Family",
    "genre": ["Drama", "Family"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "Amazon MiniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 9.0,
     "imagepath": "/bollyimages/18.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Little Things",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2016,
    "seasons": 4,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/19.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Tripling",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2016,
    "seasons": 3,
    "where_to_watch": "Zee5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/20.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Selection Day",
    "genre": ["Drama", "Sport"],
    "year_of_release": 2018,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/21.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Bard of Blood",
    "genre": ["Action", "Espionage", "Thriller"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/22.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Leila",
    "genre": ["Drama", "Sci-Fi", "Thriller"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 5.0,
     "imagepath": "/bollyimages/23.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Betaal",
    "genre": ["Horror", "Thriller"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 5.4,
     "imagepath": "/bollyimages/24.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bombay Begums",
    "genre": ["Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 4.9,
     "imagepath": "/bollyimages/25.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Taj Mahal 1989",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/26.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hasmukh",
    "genre": ["Comedy", "Crime", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 5.7,
     "imagepath": "/bollyimages/27.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Decoupled",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/28.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Jamtara",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/29.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "She",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 6.4,
     "imagepath": "/bollyimages/30.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Class",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/31.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Rana Naidu",
    "genre": ["Crime", "Drama", "Action"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/32.jpg",
    "languages": ["Hindi", "Telugu"]
  },
  {
    "title": "Scoop",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.7,
     "imagepath": "/bollyimages/33.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "CAT",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/34.jpg",
    "languages": ["Hindi", "Punjabi"]
  },
  {
    "title": "Trial by Fire",
    "genre": ["Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/35.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Guns & Gulaabs",
    "genre": ["Comedy", "Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/36.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Railway Men",
    "genre": ["Drama", "History"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/37.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mumbai Diaries",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/prime.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/38.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Rocket Boys",
    "genre": ["Biography", "Drama", "History"],
    "year_of_release": 2022,
    "seasons": 2,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.9,
     "imagepath": "/bollyimages/39.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Scam 1992",
    "genre": ["Biography", "Crime", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 9.3,
     "imagepath": "/bollyimages/40.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Scam 2003",
    "genre": ["Biography", "Crime", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/41.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Maharani",
    "genre": ["Drama", "Political"],
    "year_of_release": 2021,
    "seasons": 3,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/42.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Undekhi",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2020,
    "seasons": 3,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/43.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Your Honor",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/44.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Avrodh",
    "genre": ["Action", "Drama", "War"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/45.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Tanaav",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/46.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "College Romance",
    "genre": ["Comedy", "Romance"],
    "year_of_release": 2018,
    "seasons": 4,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/47.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Engineering Girls",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/48.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "What The Folks",
    "genre": ["Comedy", "Drama", "Family"],
    "year_of_release": 2017,
    "seasons": 4,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 8.6,
     "imagepath": "/bollyimages/49.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Cheesecake",
    "genre": ["Comedy", "Drama", "Romance"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/50.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Aam Aadmi Family",
    "genre": ["Comedy", "Drama", "Family"],
    "year_of_release": 2016,
    "seasons": 4,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/51.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Operation MBBS",
    "genre": ["Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 8.6,
     "imagepath": "/bollyimages/52.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Girls Hostel",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/53.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Please Find Attached",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/54.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Adulting",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/55.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Cubicles",
    "genre": ["Drama"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.6,
     "imagepath": "/bollyimages/56.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Brochara",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/57.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Zeroes",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/59.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Great Indian Dysfunctional Family",
    "genre": ["Drama", "Family"],
    "year_of_release": 2018,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/60.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Broken But Beautiful",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 8.6,
     "imagepath": "/bollyimages/61.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kehne Ko Humsafar Hain",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/62.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Karrle Tu Bhi Mohabbat",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2017,
    "seasons": 3,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/63.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Married Woman",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/64.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Fittrat",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/65.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "It Happened in Calcutta",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/66.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dev DD",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2017,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/67.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Puncch Beat",
    "genre": ["Drama", "Teen"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/68.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Apharan",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 8.3,
     "imagepath": "/bollyimages/69.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Raktanchal",
    "genre": ["Action", "Crime", "Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/70.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bhaukaal",
    "genre": ["Action", "Crime", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/71.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ek Thi Begum",
    "genre": ["Crime", "Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/72.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Matsya Kaand",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/73.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dharavi Bank",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/74.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Aashram",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2020,
    "seasons": 3,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/75.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Shiksha Mandal",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.7,
     "imagepath": "/bollyimages/76.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Abhay",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/78.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Sunflower",
    "genre": ["Crime", "Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/79.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kaali",
    "genre": ["Action", "Thriller"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/80.jpg",
    "languages": ["Hindi", "Bengali"]
  },
  {
    "title": "Code M",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/81.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Test Case",
    "genre": ["Drama", "War"],
    "year_of_release": 2017,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/82.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bekaaboo",
    "genre": ["Thriller", "Erotic"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.0,
     "imagepath": "/bollyimages/83.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Gandii Baat",
    "genre": ["Adult", "Drama", "Romance"],
    "year_of_release": 2018,
    "seasons": 6,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 3.5,
     "imagepath": "/bollyimages/84.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "XXX: Uncensored",
    "genre": ["Adult", "Drama"],
    "year_of_release": 2018,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 3.9,
     "imagepath": "/bollyimages/85.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hello Mini",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/86.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Twisted",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2017,
    "seasons": 2,
    "where_to_watch": "JioCinema",
    "iconpath": "/icons/jiocinema.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/87.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ragini MMS: Returns",
    "genre": ["Horror", "Erotic"],
    "year_of_release": 2017,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 4.1,
     "imagepath": "/bollyimages/88.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mastram",
    "genre": ["Drama", "Erotic"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.7,
     "imagepath": "/bollyimages/89.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Virgin Bhasskar",
    "genre": ["Comedy", "Romance"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/90.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mona Home Delivery",
    "genre": ["Drama", "Adult"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.3,
     "imagepath": "/bollyimages/91.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Woodpecker",
    "genre": ["Drama", "Adult"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.0,
     "imagepath": "/bollyimages/92.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Charmsukh",
    "genre": ["Adult", "Drama"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.2,
     "imagepath": "/bollyimages/93.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Palang Tod",
    "genre": ["Adult", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.4,
     "imagepath": "/bollyimages/94.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ratri Ke Yatri",
    "genre": ["Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 6.6,
     "imagepath": "/bollyimages/95.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Prabha Ki Diary",
    "genre": ["Drama", "Adult"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.1,
     "imagepath": "/bollyimages/96.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kavita Bhabhi",
    "genre": ["Drama", "Adult"],
    "year_of_release": 2020,
    "seasons": 3,
    "where_to_watch": "ULLU",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 4.8,
     "imagepath": "/bollyimages/97.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "MX TakaTak Fame House",
    "genre": ["Reality", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 4.5,
     "imagepath": "/bollyimages/98.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Runaway Lugaai",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/99.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Who’s Your Daddy?",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 4.3,
     "imagepath": "/bollyimages/100.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "City of Dreams",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2019,
    "seasons": 3,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.7,
     "imagepath": "/bollyimages/101.jpg",
    "languages": ["Hindi", "Tamil", "Telugu"]
  },
  {
    "title": "Chutzpah",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/102.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Roohaniyat",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 2,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/103.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ramyug",
    "genre": ["Mythology", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 4.8,
     "imagepath": "/bollyimages/104.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Marzi",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/105.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Love OK Please",
    "genre": ["Reality", "Romance"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 6.0,
     "imagepath": "/bollyimages/106.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Udan Patolas",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/107.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hiccups & Hookups",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Lionsgate Play",
    "iconpath": "/icons/lionsgate.png",
    "imdb_rating": 6.6,
     "imagepath": "/bollyimages/108.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Feels Like Home",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2022,
    "seasons": 2,
    "where_to_watch": "Lionsgate Play",
    "iconpath": "/icons/lionsgate.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/109.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Pavitra Rishta: It's Never Too Late",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 5.9,
     "imagepath": "/bollyimages/110.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Naxalbari",
    "genre": ["Thriller", "Action"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/111.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Crashh",
    "genre": ["Drama", "Family"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/112.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Zindabaad",
    "genre": ["Action", "Thriller"],
    "year_of_release": 2018,
    "seasons": 1,
    "where_to_watch": "Eros Now",
    "iconpath": "/icons/erosnow.png",
    "imdb_rating": 6.1,
     "imagepath": "/bollyimages/113.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dr. Arora",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/114.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Lock Upp",
    "genre": ["Reality", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 5.0,
     "imagepath": "/bollyimages/115.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Thinkal Kalamaan",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.4,
     "imagepath": "/bollyimages/116.jpg",
    "languages": ["Malayalam"]
  },
  {
    "title": "United Kacche",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/117.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Unpaused",
    "genre": ["Drama", "Anthology"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/118.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kaun Banegi Shikharwati",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.6,
     "imagepath": "/bollyimages/119.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Lineup",
    "genre": ["Talk Show"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/120.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Glitch",
    "genre": ["Sci-Fi", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/121.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Date Gone Wrong",
    "genre": ["Romance", "Comedy"],
    "year_of_release": 2018,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.1,
     "imagepath": "/bollyimages/122.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Metro Park",
    "genre": ["Comedy"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Eros Now",
    "iconpath": "/icons/erosnow.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/123.jpg",
    "languages": ["Hindi", "English"]
  },
  {
    "title": "Mentalhood",
    "genre": ["Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/124.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Black Widows",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/125.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Chakravyuh",
    "genre": ["Thriller", "Crime"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/126.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Masoom",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/127.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Happy Family: Conditions Apply",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/128.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Half CA",
    "genre": ["Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/129.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Minus One",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "Lionsgate Play",
    "iconpath": "/icons/lionsgate.png",
    "imdb_rating": 7.7,
     "imagepath": "/bollyimages/130.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Rafta Rafta",
    "genre": ["Romance", "Comedy"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/131.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Tiktiki",
    "genre": ["Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/132.jpg",
    "languages": ["Bengali"]
  },
  {
    "title": "The Great Weddings of Munnes",
    "genre": ["Comedy"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/133.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ghar Waapsi",
    "genre": ["Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.3,
     "imagepath": "/bollyimages/134.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ek Extra Mile",
    "genre": ["Drama", "Short"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/135.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Yeh Kaali Kaali Ankhein",
    "genre": ["Thriller", "Romance"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/136.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mukhbir – The Story of a Spy",
    "genre": ["Spy", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/137.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Adhura",
    "genre": ["Horror", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/138.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ishq Express",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/139.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Saas Bahu Aur Flamingo",
    "genre": ["Crime", "Action"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/140.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hunter",
    "genre": ["Action", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/amazon.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/141.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ishq Mein Marjawan",
    "genre": ["Romance", "Thriller"],
    "year_of_release": 2017,
    "seasons": 3,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/142.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Swaran Ghar",
    "genre": ["Drama", "Family"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/143.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Paap",
    "genre": ["Thriller", "Mystery"],
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Hoichoi",
    "iconpath": "/icons/hoichoi.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/145.jpg",
    "languages": ["Bengali"]
  },
  {
    "title": "Saala Salil",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "PrimeShots",
    "iconpath": "/icons/primeshots.png",
    "imdb_rating": 6.0,
     "imagepath": "/bollyimages/146.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dil Dosti Dilemma",
    "genre": ["Drama", "Coming-of-Age"],
    "year_of_release": 2024,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/147.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Pop Kaun?",
    "genre": ["Comedy"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 6.1,
     "imagepath": "/bollyimages/148.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Chamak",
    "genre": ["Musical", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/149.jpg",
    "languages": ["Hindi", "Punjabi"]
  },
  {
    "title": "The Freelancer",
    "genre": ["Thriller", "Action"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/150.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Karm Yuddh",
    "genre": ["Drama", "Politics"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/151.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kaala",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/152.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dil Bekaraar",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/153.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Potluck",
    "genre": ["Comedy", "Family"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/154.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Jehanabad Diaries",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/155.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Pill",
    "genre": ["Medical", "Drama"],
    "year_of_release": 2024,
    "seasons": 1,
    "where_to_watch": "JioCinema",
    "iconpath": "/icons/jiocinema.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/157.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Half Pants Full Pants",
    "genre": ["Family", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/158.jpg",
    "languages": ["Hindi", "Kannada"]
  },
  {
    "title": "Jhansi",
    "genre": ["Action", "Thriller"],
    "year_of_release": 2022,
    "seasons": 2,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/159.jpg",
    "languages": ["Telugu", "Hindi", "Tamil"]
  },
  {
    "title": "Six",
    "genre": ["Mystery", "Thriller"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 6.6,
     "imagepath": "/bollyimages/160.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Verdict – State vs Nanavati",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.2,
     "imagepath": "/bollyimages/161.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ek Duje Ke Vaaste 2",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/162.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Inspector Avinash",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/163.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Taali",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/164.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Baked",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/165.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "NRI Haadsa",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/166.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "CyberSquad",
    "genre": ["Action", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/167.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Anamika",
    "genre": ["Mystery", "Thriller"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/168.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "London Files",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/169.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Duranga",
    "genre": ["Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/170.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Sultan of Delhi",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/171.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Pashminna – Dhaage Mohabbat Ke",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/172.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Lalbazaar",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/173.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Girgit",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/174.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Who’s Your Gynac?",
    "genre": ["Documentary"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/175.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "I Love Us",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/176.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mithya",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/177.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Raikar Case",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/178.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Out of Love",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/179.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "BhagyaLakshmi",
    "genre": ["Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/180.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Chhatrasal",
    "genre": ["Historical", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/181.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Tere Ishq Mein Ghayal",
    "genre": ["Romance", "Supernatural"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "JioCinema",
    "iconpath": "/icons/jiocinema.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/182.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Modern Love: Mumbai",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.9,
     "imagepath": "/bollyimages/183.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Modern Love: Hyderabad",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/184.jpg",
    "languages": ["Telugu"]
  },
  {
    "title": "Modern Love: Chennai",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 7.8,
     "imagepath": "/bollyimages/185.jpg",
    "languages": ["Tamil"]
  },
  {
    "title": "Hadd",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/187.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Class of 2020",
    "genre": ["Drama", "Teen"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.6,
     "imagepath": "/bollyimages/188.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Class of 2017",
    "genre": ["Drama", "Teen"],
    "year_of_release": 2017,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/189.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Zindagi inShort",
    "genre": ["Anthology", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.2,
     "imagepath": "/bollyimages/190.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Kaun? Who Did It?",
    "genre": ["Crime", "Mystery"],
    "year_of_release": 2021,
    "seasons": 2,
    "where_to_watch": "Flipkart Video",
    "iconpath": "/icons/flipkart",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/192.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Crime Stories: India Detectives",
    "genre": ["Crime", "Documentary"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/193.jpg",
    "languages": ["Hindi", "Kannada"]
  },
  {
    "title": "Indian Predator: The Butcher of Delhi",
    "genre": ["Crime", "Documentary"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/194.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Indian Predator: The Diary of a Serial Killer",
    "genre": ["Crime", "Documentary"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/195.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Indian Predator: Murder in a Courtroom",
    "genre": ["Crime", "Documentary"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/196.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Tooth Pari: When Love Bites",
    "genre": ["Fantasy", "Romance"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/197.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Rocket Gang: The Series",
    "genre": ["Musical", "Dance"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/198.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "MTV Girls on Top",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2016,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/199.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "MTV Webbed",
    "genre": ["Crime", "Teen"],
    "year_of_release": 2013,
    "seasons": 2,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/200.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "MTV Warrior High",
    "genre": ["Drama", "Teen"],
    "year_of_release": 2015,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 6.4,
     "imagepath": "/bollyimages/201.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Badtameez Dil",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/203.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Inspector Rishi",
    "genre": ["Horror", "Thriller"],
    "year_of_release": 2024,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/204.jpg",
    "languages": ["Tamil", "Hindi", "Telugu"]
  },
  {
    "title": "Vadhuvu",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/205.jpg",
    "languages": ["Telugu"]
  },
  {
    "title": "Shaitan",
    "genre": ["Crime", "Thriller"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 7.4,
     "imagepath": "/bollyimages/206.jpg",
    "languages": ["Telugu", "Hindi"]
  },
  {
    "title": "Killer Soup",
    "genre": ["Dark Comedy", "Thriller"],
    "year_of_release": 2024,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 7.3,
     "imagepath": "/bollyimages/207.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Trial Period",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "JioCinema",
    "iconpath": "/icons/jiocinema.png",
    "imdb_rating": 6.1,
     "imagepath": "/bollyimages/208.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Sandeep Bhaiya",
    "genre": ["Drama", "Inspirational"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 9.1,
     "imagepath": "/bollyimages/209.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "100",
    "genre": ["Action", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 5.6,
     "imagepath": "/bollyimages/210.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ghar Wapasi",
    "genre": ["Drama", "Family"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.4,
     "imagepath": "/bollyimages/211.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Holiday",
    "genre": ["Drama", "Comedy"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "MX Player",
    "iconpath": "/icons/mxplayer.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/212.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Main Monica",
    "genre": ["Crime", "Comedy"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/213.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dr. Don",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2020,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.6,
     "imagepath": "/bollyimages/214.jpg",
    "languages": ["Marathi"]
  },
  {
    "title": "Kashmakash",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Hungama Play",
    "iconpath": "/icons/hungama",
    "imdb_rating": 6.0,
     "imagepath": "/bollyimages/215.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Tandoori Idly",
    "genre": ["Romance", "Comedy"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/216.jpg",
    "languages": ["Tamil"]
  },
  {
    "title": "Bali",
    "genre": ["Horror", "Mystery"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/217.jpg",
    "languages": ["Marathi"]
  },
  {
    "title": "Black Coffee",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Ullu",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.8,
     "imagepath": "/bollyimages/218.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Dev DD",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2017,
    "seasons": 2,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.1,
     "imagepath": "/bollyimages/219.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "College Detectives",
    "genre": ["Mystery", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 6.5,
     "imagepath": "/bollyimages/221.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Jab We Matched",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 6.7,
     "imagepath": "/bollyimages/222.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ghar Set Hai",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "Amazon miniTV",
    "iconpath": "/icons/minitv.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/223.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mission Over Mars (M.O.M.)",
    "genre": ["Drama", "Sci-Fi"],
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.8,
     "imagepath": "/bollyimages/224.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bebakee",
    "genre": ["Romance", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/225.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "It Happened in Calcutta",
    "genre": ["Drama", "Romance"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/227.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Palang Tod",
    "genre": ["Drama", "Erotic"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Ullu",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 5.3,
     "imagepath": "/bollyimages/230.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Matki",
    "genre": ["Drama", "Erotic"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "Ullu",
    "iconpath": "/icons/ullu.png",
    "imdb_rating": 4.8,
     "imagepath": "/bollyimages/231.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Charitraheen",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2018,
    "seasons": 3,
    "where_to_watch": "Hoichoi",
    "iconpath": "/icons/hoichoi.png",
    "imdb_rating": 6.9,
     "imagepath": "/bollyimages/234.jpg",
    "languages": ["Bengali", "Hindi"]
  },
  {
    "title": "Dupur Thakurpo",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2017,
    "seasons": 3,
    "where_to_watch": "Hoichoi",
    "iconpath": "/icons/hoichoi.png",
    "imdb_rating": 6.2,
     "imagepath": "/bollyimages/235.jpg",
    "languages": ["Bengali"]
  },
  {
    "title": "Khela",
    "genre": ["Drama", "Thriller"],
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Addatimes",
    "iconpath": "/icons/addatimes",
    "imdb_rating": 6.3,
     "imagepath": "/bollyimages/236.jpg",
    "languages": ["Bengali"]
  },
  {
    "title": "Naked",
    "genre": ["Thriller", "Drama"],
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 5.8,
     "imagepath": "/bollyimages/237.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Faltu Engineers",
    "genre": ["Comedy", "Drama"],
    "year_of_release": 2017,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/239.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Rangbaaz: Darr Ki Rajneeti",
    "genre": ["Crime", "Drama"],
    "year_of_release": 2022,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.5,
     "imagepath": "/bollyimages/240.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Jamai Raja 2.0",
    "genre": "Drama",
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.3,
      "imagepath": "/bollyimages/241.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Shiddat (Web Extension)",
    "genre": "Romance",
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 6.5,
      "imagepath": "/bollyimages/242.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Sankat Mochan Mahabali Hanuman",
    "genre": "Mythological",
    "year_of_release": 2015,
    "seasons": 1,
    "where_to_watch": "SonyLIV",
    "iconpath": "/icons/sonyliv.png",
    "imdb_rating": 8.1,
      "imagepath": "/bollyimages/243.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Ramayan (2008)",
    "genre": "Mythological",
    "year_of_release": 2008,
    "seasons": 1,
    "where_to_watch": "YouTube",
    "iconpath": "/icons/youtube.png",
    "imdb_rating": 7.9,
      "imagepath": "/bollyimages/244.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mahabharat (2013)",
    "genre": "Mythological",
    "year_of_release": 2013,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 9.1,
      "imagepath": "/bollyimages/245.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Jhansi Ki Rani",
    "genre": "Historical Drama",
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.0,
      "imagepath": "/bollyimages/246.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bal Shiv",
    "genre": "Mythological",
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 7.6,
      "imagepath": "/bollyimages/248.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Naagin (Web Spin-off)",
    "genre": "Supernatural",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Voot",
    "iconpath": "/icons/voot.png",
    "imdb_rating": 5.8,
      "imagepath": "/bollyimages/249.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Vaat Vaat Ma",
    "genre": "Comedy, Family",
    "year_of_release": 2023,
    "seasons": 1,
    "where_to_watch": "ShemarooMe",
    "iconpath": "/icons/shemaroo.png",
    "imdb_rating": 7.2,
      "imagepath": "/bollyimages/251.jpg",
    "languages": ["Gujarati"]
  },
  {
    "title": "Love Bites",
    "genre": "Romance",
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.9,
      "imagepath": "/bollyimages/252.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Casino",
    "genre": "Thriller",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 5.7,
      "imagepath": "/bollyimages/253.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "P.O.W. - Bandi Yuddh Ke",
    "genre": "Drama, War",
    "year_of_release": 2016,
    "seasons": 1,
    "where_to_watch": "Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.5,
     "imagepath": "/bollyimages/254.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Office (India)",
    "genre": "Comedy, Mockumentary",
    "year_of_release": 2019,
    "seasons": 2,
    "where_to_watch": "Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 5.9,
     "imagepath": "/bollyimages/255.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "BOSS: Baap of Special Services",
    "genre": "Action, Thriller",
    "year_of_release": 2019,
    "seasons": 1,
    "where_to_watch": "ALTBalaji",
    "iconpath": "/icons/altbalaji.png",
    "imdb_rating": 7.0,
     "imagepath": "/bollyimages/256.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Love, Scandal & Doctors",
    "genre": "Thriller, Mystery",
    "year_of_release": 2021,
    "seasons": 1,
    "where_to_watch": "ZEE5",
    "iconpath": "/icons/zee5.png",
    "imdb_rating": 6.4,
     "imagepath": "/bollyimages/257.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Farzi",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/260.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Bandish Bandits",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/261.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Aarya",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/262.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Four More Shots Please!",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/263.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Hostages",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/264.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "JL50",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/265.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Permanent Roommates",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/266.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Sacred Games",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/267.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Special OPS",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/268.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Power of Paanch",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/269.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Chidiya Udd",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/270.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Adolescence",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/271.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Heeramandi",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Netflix",
    "iconpath": "/icons/netflix.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/272.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Mismatched",
    "genre": "Drama",
    "year_of_release": 2024,
    "seasons": 3,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/273.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Call Me Bae",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/274.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Taaza Khabar",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/275.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "The Legend of Hanuman",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Disney+ Hotstar",
    "iconpath": "/icons/hotstar.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/276.jpg",
    "languages": ["Hindi"]
  },
  {
    "title": "Reacher",
    "genre": "Drama",
    "year_of_release": 2020,
    "seasons": 1,
    "where_to_watch": "Amazon Prime Video",
    "iconpath": "/icons/primevideo.png",
    "imdb_rating": 8.0,
     "imagepath": "/bollyimages/277.png",
    "languages": ["Hindi"]
  }
];

  
  module.exports={data: bollyser};
  
  
  
  